# Generated by Django 2.2.4 on 2019-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
